---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: discord
  namespace: default
spec:
  channel: flux-lab
  secretRef:
    name: dscord
  type: discord
  username: FluxBot

